### ISSUE TITLE
Detected blocking call to import_module (this one in `api.py`)

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#492] opened 2024-05-06 07:57 UTC
### Describe the issue

Updated to most recent and noticed these `warning` started showing up. Similar to #488, but in a different file.

```
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 07:23:53 (9 occurrences)
Last logged: 09:23:55

Detected blocking call to import_module inside the event loop by custom integration 'energidataservice' at custom_components/energidataservice/api.py, line 236: forecast_module = import_module( (offender: /config/custom_components/energidataservice/api.py, line 236: forecast_module = import_module(), please create a bug report at https://github.com/MTrab/energidataservice/issues
Detected blocking call to import_module inside the event loop by custom integration 'energidataservice' at custom_components/energidataservice/api.py, line 106: module = import_module( (offender: /config/custom_components/energidataservice/api.py, line 106: module = import_module(), please create a bug report at https://github.com/MTrab/energidataservice/issues
```

### What version of Home Assistant Core has the issue?

core-2024.5.1

### What was the last working version of Home Assistant Core?

None

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

### Anything in the logs that might be useful for us?

None

### Additional information

None

**Comment by MTrab** [comment] 2024-05-06 11:27
Duplicate of #488

**Closed by MTrab** 2024-05-06 11:27 UTC
Labels: bug
