### ISSUE TITLE
Make it possible to get price for sale to the grid from solar panels

### ISSUE THREAD

**Issue by jensrosendaljensen** [MTrab/energidataservice#330] opened 2023-07-14 20:22 UTC
### Describe the feature you wish to make a request for

When you have a solar plant and you are selling your excess power back to the grid.
This is done by using the nord pool prices minus some tarrifs.
I am using vindstød and they explain the price model on this page 
https://www.vindstoed.dk/tilmelding-solcelle

Børsens spotpris (*)	125,0000 øre/kWh
Energinets indfødningstarif	-0,3750 øre/kWh
Energinets balancetarif	-0,1600 øre/kWh
Netselskabets indfødningstarif (**)	-5,20 øre/kWh
Vindstøds balancetarif	-1,0000 øre/kWh
Din kWh pris	118,265 **øre/kWh**

Additional info

It would be cool if it was possible to choose 
Export power prices.

### Describe alternatives you've considered

It might be possible to use your template and use minus in stead

**Comment by MTrab** [comment] 2023-07-15 02:34
Duplicate of #203

**Closed by MTrab** 2023-07-15 02:34 UTC
Labels: feature request
