### ISSUE TITLE
Possible calculation issue? (Not sure)

### ISSUE THREAD

**Issue by geekgarage** [MTrab/energidataservice#433] opened 2024-01-31 13:38 UTC
### Describe the issue

So I noticed a difference between my HA sensor (showing too high a price) with the raw kWh price including VAT, and if I did the calculation myself using Nord Pool. It's minuscule, in my example 0,0003 DKK, but it's there.
the difference over a year is so little that I don't vare, i just want to make sure that it's not some exponential thing that suddenly shows way off
![image](https://github.com/MTrab/energidataservice/assets/12700648/9edfaf4d-c983-4cdb-a3fb-2dd9bb45a572)

### What version of Home Assistant Core has the issue?

core-2024.1.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-01-31T13-11-31.591Z.log](https://github.com/MTrab/energidataservice/files/14112291/home-assistant_energidataservice_2024-01-31T13-11-31.591Z.log)
(I sanitized the log for no relevant stuff regarding my other sensors

### Anything in the logs that might be useful for us?

```txt
not that i see, it starts fin, fetches prices just fine. I think it's either som decimal difference or exchange rate issue as i can see in the logs prices are retrieved in Euros instead of DKK
```

**Comment by MTrab** [comment] 2024-01-31 14:19
Duplicate of #425

**Closed by MTrab** 2024-01-31 14:19 UTC
Labels: bug

**Comment by geekgarage** [comment] 2024-02-04 13:13
I figured out the issue. The added cost should be without VAT as when you tick the "Include VAT" when configuring it, it is adding the VAT to the float as well. So I just used the price my sheet calculated for me for kWh, but without VAT, and then it's showing the correct price matching Norlys
