### ISSUE TITLE
API request: 400, message='Bad Request'

### ISSUE THREAD

**Issue by HrCalmar** [MTrab/energidataservice#639] opened 2024-11-12 21:02 UTC
### Describe the issue

Efter en genstart starter EDS ikke korrekt op.

Modtager følgende fejl:
"Error during API request: 400, message='Bad Request', url='https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500'"

### What version of Home Assistant Core has the issue?

core-2024.11.1

### What was the last working version of Home Assistant Core?

core-2024.11.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_2024-11-12T20-59-06.947Z.log](https://github.com/user-attachments/files/17722744/home-assistant_2024-11-12T20-59-06.947Z.log)

**Comment by Chreutz** [comment] 2024-11-12 21:11
Jeg ser det samme. Jeg ved ikke om energidataservice har et problem med deres API eller om de har lavet det om, men der ser ikke (i skrivende stund) ud til at være nogen felter i https://api.energidataservice.dk/dataset/DatahubPricelist hvor Note-feltet indeholder noget om Elafgift, Systemtarif etc.

**Comment by lassealfastsen** [comment] 2024-11-12 21:41
+1 på denne, jeg har fuldstændig det samme.

**Comment by Jogistar** [comment] 2024-11-12 21:47
Samme her

**Comment by Bredum** [comment] 2024-11-13 05:33
Samme her

**Comment by MTrab** [comment] 2024-11-13 05:43
Duplicate of #638

**Closed by MTrab** 2024-11-13 05:43 UTC
Labels: bug

**Comment by kejXero** [comment] 2024-11-13 06:32
Is the solution to wait for energidataservice to fix this? as I have the same problem now.

This error originated from a custom integration.

Logger: custom_components.energidataservice.connectors.energidataservice
Source: custom_components/energidataservice/connectors/energidataservice/__init__.py:120
integration: Energi Data Service (documentation, issues)
First occurred: 07:14:34 (2 occurrences)
Last logged: 07:19:39

API returned error 400, Bad Request!

**Comment by MTrab** [comment] 2024-11-13 06:36
Follow then other issue, this is closed as it's a duplicate
