### ISSUE TITLE
Energidata gives erro when setup

### ISSUE THREAD

**Issue by Coolltazz** [MTrab/energidataservice#181] opened 2023-01-08 12:59 UTC
## Additional cost template

```text

{{0|float}}

```

## Describe the bug
energidataservice is unavailable after setup.

## Debug log

```text

2023-01-08 13:09:53.659 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration panasonic_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:09:53.663 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:09:53.666 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:09:53.668 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:09:53.670 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ihc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:09:53.672 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration energidataservice which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-08 13:10:16.135 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform energidataservice is taking over 10 seconds.
2023-01-08 13:10:16.142 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform energidataservice is taking over 10 seconds.
2023-01-08 13:10:17.629 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 259, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 618, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 582, in _calculate
    price += float(self._api.tariff_data["tariffs"][str(hour.hour)]) * (
KeyError: '0'
2023-01-08 13:10:17.757 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 259, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 618, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 582, in _calculate
    price += float(self._api.tariff_data["tariffs"][str(hour.hour)]) * (
KeyError: '0'
2023-01-08 13:10:53.127 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'


```

## Diganostics data from the device

```text

Add your diagnostics here.

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.8",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "panasonic_cc": {
      "version": "1.0.32",
      "requirements": []
    },
    "audiconnect": {
      "version": "2021.1.1",
      "requirements": [
        "beautifulsoup4"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "blueiris": {
      "version": "1.0.15",
      "requirements": []
    },
    "ihc": {
      "version": "2022.10.0",
      "requirements": [
        "defusedxml==0.6.0",
        "ihcsdk==2.7.6"
      ]
    },
    "energidataservice": {
      "version": "1.0.0",
      "requirements": [
        "CurrencyConverter==0.17.4",
        "pyeloverblik==0.3.1"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "CurrencyConverter==0.17.4",
      "pyeloverblik==0.3.1"
    ],
    "version": "1.0.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "057273438e2a631393cdc6e5feb8df0e",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service",
      "data": {
        "name": "Energi Data Service"
      },
      "options": {
        "enable_forecast": false,
        "area": "East of the great belt",
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0|float}}",
        "name": "Energi Data Service",
        "country": "Denmark",
        "email": "**REDACTED**",
        "api_key": "**REDACTED**",
        "enable_tariffs": true,
        "tariff_charge_owner": "Radius Elnet AS"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "today_calculated": false,
    "api_today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "tomorrow_calculated": false,
    "api_tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "predictions": null,
    "api_predictions": null,
    "tariff_data": {
      "additional_tariffs": {
        "transmissions_net_tarif": 0.058,
        "system_tarif": 0.054,
        "el_afgift": 0.008
      },
      "tariffs": {}
    },
    "next_update": "13:24:36",
    "data_source": "Energi Data Service",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}

**Comment by MTrab** [comment] 2023-01-08 13:00
Duplicate of #175

**Closed by MTrab** 2023-01-08 13:00 UTC
