### ISSUE TITLE
Integration does not calculate tomorrows prices using tomorrows tariffs

### ISSUE THREAD

**Issue by KennethLavrsen** [MTrab/energidataservice#245] opened 2023-01-31 14:22 UTC
### Environment:

- Home Assistant version: 2023.1.7
- Energidatastyrelsen version: 1.1.2
- Operation system: HAOS

## Configuration

Example:
- Country: Denmark
- Region: East of..
- Show in cents: No
- Show prices Including VAT: yes

## Additional cost template

```text

{{0.0456|float}}

```

The integration uses todays tariffs when it calculates tomorrows prices.

That is not a problem most of the time. Except today as I record this bug on January 31st.
Tariffs change 1st of February (increase).

I have calculated the prices manually and I can see that the integration does not use the tarifs for February when it calculate tariffs for tomorrow. And that will repeat itself on 28th  of February where it prices will be too high because the tariffs drop again in March.

Does Energi Data Service even have the data for tariffs next day or next month?

I also have a sensor using Nordpool where I calculate tariffs myself based on a matrix that I have to keep up to date myself. That shows the right price.

But I was hoping this integration would do the boring job for me so I can drop my own solution

Edit. It also misses tariff change 1st of month. You have to reload integration or restart HA to get it to update. Still wrong at 9am on Feb 1st

**Comment by MTrab** [comment] 2023-01-31 14:56
Not a bug as such, it's a lack of feature.
Currently only the tariffs for the current day is used, for all days.
It reloads daily

**Comment by KennethLavrsen** [comment] 2023-02-01 08:06
I can add today the 1st of February that the integration uses the January tariffs even if it is now February.

After a restart of home assistant the integration reloads the tariffs and the price is correct again.

Either the integration does not reload tariffs after midnight or the source it loads from is delayed so you miss the update

**Comment by MTrab** [comment] 2023-02-01 09:39
Yeah - noticed yesterday that I had the tariff refresh alongside the price refresh and not at midnight.
That will be fixed in next release.

**Comment by KennethLavrsen** [comment] 2023-03-01 10:23
The problem happened again here on March 1st. February tarifs were used until I restarted Home Assistant

**Comment by KennethLavrsen** [comment] 2023-03-31 22:54
April 1st and again the prices are calculated using tarifs from March 31st. Even if I reload the integration it insists on using yesterdays tarifs.

**Comment by nikobh** [comment] 2023-04-12 16:23
Some tariffs have different values depending on weekday etc. so for these it would be great to have a daily tariff refresh to avoid having issues each Saturday and Monday.

**Comment by MTrab** [comment] 2023-04-12 17:22
> Some tariffs have different values depending on weekday etc. so for these it would be great to have a daily tariff refresh to avoid having issues each Saturday and Monday.

Tariffs refresh at midnight every day, so this is already a thing

**Comment by nikobh** [comment] 2023-04-12 19:21
> > Some tariffs have different values depending on weekday etc. so for these it would be great to have a daily tariff refresh to avoid having issues each Saturday and Monday.
> 
> Tariffs refresh at midnight every day, so this is already a thing

Yes - and that is good :-)
But if I have one set of hourly tariff-rates on a Friday and another set on the following Saturday, the price (spot+tariff+VAT) for Saturday will be calculated wrongly all Friday until the tariff-refresh or a restart of home assistant. 
So I don't know how, but it would be great if the tariffs for 'today' and 'tomorrow' - just as the spot prices are fetched.

**Comment by KennethLavrsen** [comment] 2023-04-12 20:57
Exact same problem I reported.
The problem is not that the tariffs are not updated daily. The problem is that tomorrows prices are calculated with todays tariffs. To get it right the software need to load todays and tomorrows tariffs and use that dataset of 48 hourly values to calculate prices for rest of today and all of tomorrow. As far as I can tell the data is available at the EDS site.

**Comment by MTrab** [comment] 2023-04-13 08:53
But it DOES auto refresh - every day at midnight.

True that it uses todays tariff for today, tomorrow and forecasts too, haven't had the time to make the changes to use the correct pr. day tariffs.

**Comment by nikobh** [comment] 2023-04-13 10:28
Cool - Thanks for your effort!

**Comment by nikobh** [comment] 2023-04-15 08:42
> But it DOES auto refresh - every day at midnight.
> 
The tariff changed to weekend tariff today, but not until I reloaded the integration in HA. So the midnight update doesn't kick in. If I knew how to fix I'd give it a shot, but now I'm looking for a way to auto-reload the integration every night at 04.00.

**Comment by MTrab** [comment] 2023-04-15 09:02
See, that's a whole other issue then, because the integration has autoreload of tariffs as well as the prices at midnight.

**Comment by nikobh** [comment] 2023-04-15 09:46
![Skærmbillede 2023-04-15 114349](https://user-images.githubusercontent.com/45816930/232206361-eaa1010a-cde0-4bec-96e2-455908580fad.png)
This is a screendump from my installation right now at 11.44 Saturday. The tariff is 0,074 all day on Saturdays and this is the tariff as refreshed yesterday. I think it will refresh at the midday update, but it seems that the midnight update isn't working.

**Comment by MTrab** [comment] 2023-04-15 09:55
Please create an issue for this, as it is not related to this issue.

**Closed** 2023-06-20 11:01 UTC
Labels: enhancement, feature planned
