### ISSUE TITLE
Not updating at midnight as expected.

### ISSUE THREAD

**Issue by PeterAndreS** [MTrab/energidataservice#357] opened 2023-09-05 08:28 UTC
### Describe the issue

Not updating at midnight as expected, only on HA restart. Just installed latest version, but i expect this is a bug.

### What version of Home Assistant Core has the issue?

core-2023.8.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Just not updated after midnight.

**Comment by MTrab** [comment] 2023-09-05 09:21
Could this be a duplicate of #354 
Difficult to say without diagnistics and logs as requested!

**Comment by PeterAndreS** [comment] 2023-09-05 10:54
Can see it contacts server at midnight: And fails.
**Suggestion:** Server contact not necessary - since tomorrow's values are already known

**Log:**
2023-09-05 00:00:00.377 DEBUG (MainThread) [custom_components.energidataservice] New day function called
2023-09-05 00:00:00.377 DEBUG (MainThread) [custom_components.energidataservice.tariffs] Finding valid endpoints for region 'DK2'
2023-09-05 00:00:01.225 DEBUG (MainThread) [custom_components.energidataservice] New hour, updating state
2023-09-05 00:00:01.226 DEBUG (MainThread) [custom_components.energidataservice.sensor] Validating sensor Energi Data Service
2023-09-05 00:00:01.226 DEBUG (MainThread) [custom_components.energidataservice.sensor] Predictions: None (<class 'NoneType'>)
2023-09-05 00:00:01.226 DEBUG (MainThread) [custom_components.energidataservice.sensor] Tariff dataset before VAT: {'additional_tariffs': {'transmissions_nettarif': 0.058, 'systemtarif': 0.054, 'elafgift': 0.697}, 'tariffs': {'0': 0.1422, '1': 0.1422, '2': 0.1422, '3': 0.1422, '4': 0.1422, '5': 0.1422, '6': 0.2134, '7': 0.2134, '8': 0.2134, '9': 0.2134, '10': 0.2134, '11': 0.2134, '12': 0.2134, '13': 0.2134, '14': 0.2134, '15': 0.2134, '16': 0.2134, '17': 0.5548, '18': 0.5548, '19': 0.5548, '20': 0.5548, '21': 0.2134, '22': 0.2134, '23': 0.2134}}
2023-09-05 00:00:01.227 DEBUG (MainThread) [custom_components.energidataservice.sensor] Tariff dataset after VAT: {'additional_tariffs': {'transmissions_nettarif': 0.0725, 'systemtarif': 0.0675, 'elafgift': 0.8712}, 'tariffs': {'0': 0.1777, '1': 0.1777, '2': 0.1777, '3': 0.1777, '4': 0.1777, '5': 0.1777, '6': 0.2667, '7': 0.2667, '8': 0.2667, '9': 0.2667, '10': 0.2667, '11': 0.2667, '12': 0.2667, '13': 0.2667, '14': 0.2667, '15': 0.2667, '16': 0.2667, '17': 0.6935, '18': 0.6935, '19': 0.6935, '20': 0.6935, '21': 0.2667, '22': 0.2667, '23': 0.2667}}
2023-09-05 00:00:01.468 DEBUG (MainThread) [custom_components.energidataservice] New hour, updating state
2023-09-05 00:00:01.468 DEBUG (MainThread) [custom_components.energidataservice.sensor] Validating sensor Energi Data Service - Uden afgift
2023-09-05 00:00:01.468 DEBUG (MainThread) [custom_components.energidataservice.sensor] Predictions: None (<class 'NoneType'>)
2023-09-05 00:00:01.469 DEBUG (MainThread) [custom_components.energidataservice.sensor] Current price updated to 87.934901 for DK2
2023-09-05 00:01:32.143 ERROR (MainThread) [custom_components.energidataservice.tariffs.energidataservice] Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:03:18.026 ERROR (MainThread) [custom_components.energidataservice.tariffs.energidataservice] Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:03:54.560 ERROR (MainThread) [custom_components.energidataservice.tariffs.energidataservice] Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:04:04.531 ERROR (MainThread) [custom_components.energidataservice.tariffs.energidataservice] Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:05:00.120 INFO (MainThread) [homeassistant.components.automation.threshold_start_affugtning_i_kaelder] Threshold - Start affugtning i kælder : Executing step device automation
2023-09-05 00:05:00.383 INFO (MainThread) [homeassistant.components.automation.threshold_start_affugtning_i_kaelder] Threshold - Start affugtning i kælder : Executing step device automation
2023-09-05 00:06:15.624 ERROR (MainThread) [custom_components.energidataservice.tariffs.energidataservice] Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:06:15.624 WARNING (MainThread) [async_retrying_ng] ClientResponseError -> Attempts (5) are over for <function Connector.async_call_api at 0x7fdc3bf7b4c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/async_retrying_ng/__init__.py", line 118, in wrapped
    ret = await ret
          ^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 183, in async_call_api
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')
2023-09-05 00:06:15.627 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/async_retrying_ng/__init__.py", line 118, in wrapped
    ret = await ret
          ^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 183, in async_call_api
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/energidataservice/__init__.py", line 94, in new_day
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 230, in async_get_tariffs
    self.tariff_data = await tariff.async_get_tariffs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 59, in async_get_tariffs
    await self.async_get_system_tariffs()
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 156, in async_get_system_tariffs
    dataset = await self.async_call_api(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_retrying_ng/__init__.py", line 158, in wrapped
    raise fallback from exc
async_retrying_ng.RetryError

**Comment by MTrab** [comment] 2023-09-09 07:40
Still an issue? Can't reproduce the error. but will try to implement a better handling of server errors.

**Closed** 2023-09-09 09:39 UTC
Labels: bug
