### ISSUE TITLE
Integration fails to load when using Radius Elnet A/S

### ISSUE THREAD

**Issue by briis** [MTrab/energidataservice#183] opened 2023-01-08 13:13 UTC
### Environment:
- Home Assistant version: 2023.3.1
- Energidatastyrelsen version: 1.0.0
- Operation system: Debian - Supervised

## Configuration
- Country: Denmark
- Region: East of the great belt
- Show in cents: No
- Number of decimals: 3
- Net operator: Radius Elnet A/S

## Additional cost template
```text
{{0.0|float}}
```

## Describe the bug
The sensor never gets any data and constantly shows as `unavailable`

## Debug log

```text

Error adding entities for domain sensor with platform energidataservice
Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 408, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 259, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 618, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 582, in _calculate
    price += float(self._api.tariff_data["tariffs"][str(hour.hour)]) * (
KeyError: '0'

```

## Diganostics data from the device

```text

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "energidataservice": {
      "version": "1.0.0",
      "requirements": [
        "CurrencyConverter==0.17.4",
        "pyeloverblik==0.3.1"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "eloverblik": {
      "version": "0.2.0",
      "requirements": [
        "pyeloverblik==0.3.1"
      ]
    },
    "renoweb": {
      "version": "1.0.0",
      "requirements": [
        "pyrenoweb==1.1.1"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "CurrencyConverter==0.17.4",
      "pyeloverblik==0.3.1"
    ],
    "version": "1.0.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "979cda62dc1661295500e563dd568bb5",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service",
      "data": {
        "name": "Energi Data Service"
      },
      "options": {
        "tariff_charge_owner": "Radius Elnet A/S",
        "email": "**REDACTED**",
        "api_key": "**REDACTED**",
        "enable_forecast": true,
        "enable_tariffs": true,
        "area": "East of the great belt",
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0.0|float}}",
        "name": "Energi Data Service",
        "country": "Denmark"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "today_calculated": false,
    "api_today": [
      [
        24.440001,
        "2023-01-08T00:00:00+01:00"
      ],
      [
        9.3,
        "2023-01-08T01:00:00+01:00"
      ],
      [
        9.1,
        "2023-01-08T02:00:00+01:00"
      ],
      [
        4.16,
        "2023-01-08T03:00:00+01:00"
      ],
      [
        5.58,
        "2023-01-08T04:00:00+01:00"
      ],
      [
        9.92,
        "2023-01-08T05:00:00+01:00"
      ],
      [
        9.02,
        "2023-01-08T06:00:00+01:00"
      ],
      [
        16.469999,
        "2023-01-08T07:00:00+01:00"
      ],
      [
        27.08,
        "2023-01-08T08:00:00+01:00"
      ],
      [
        29.08,
        "2023-01-08T09:00:00+01:00"
      ],
      [
        35.220001,
        "2023-01-08T10:00:00+01:00"
      ],
      [
        70.190002,
        "2023-01-08T11:00:00+01:00"
      ],
      [
        49.080002,
        "2023-01-08T12:00:00+01:00"
      ],
      [
        65.129997,
        "2023-01-08T13:00:00+01:00"
      ],
      [
        62.189999,
        "2023-01-08T14:00:00+01:00"
      ],
      [
        63.490002,
        "2023-01-08T15:00:00+01:00"
      ],
      [
        86.290001,
        "2023-01-08T16:00:00+01:00"
      ],
      [
        118.040001,
        "2023-01-08T17:00:00+01:00"
      ],
      [
        122.610001,
        "2023-01-08T18:00:00+01:00"
      ],
      [
        65.620003,
        "2023-01-08T19:00:00+01:00"
      ],
      [
        60.98,
        "2023-01-08T20:00:00+01:00"
      ],
      [
        60.310001,
        "2023-01-08T21:00:00+01:00"
      ],
      [
        69.400002,
        "2023-01-08T22:00:00+01:00"
      ],
      [
        48.889999,
        "2023-01-08T23:00:00+01:00"
      ]
    ],
    "tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "tomorrow_calculated": false,
    "api_tomorrow": [
      [
        75.129997,
        "2023-01-09T00:00:00+01:00"
      ],
      [
        64.379997,
        "2023-01-09T01:00:00+01:00"
      ],
      [
        60.279999,
        "2023-01-09T02:00:00+01:00"
      ],
      [
        39.41,
        "2023-01-09T03:00:00+01:00"
      ],
      [
        47.34,
        "2023-01-09T04:00:00+01:00"
      ],
      [
        68.989998,
        "2023-01-09T05:00:00+01:00"
      ],
      [
        107.129997,
        "2023-01-09T06:00:00+01:00"
      ],
      [
        160.0,
        "2023-01-09T07:00:00+01:00"
      ],
      [
        180.0,
        "2023-01-09T08:00:00+01:00"
      ],
      [
        177.139999,
        "2023-01-09T09:00:00+01:00"
      ],
      [
        159.070007,
        "2023-01-09T10:00:00+01:00"
      ],
      [
        160.570007,
        "2023-01-09T11:00:00+01:00"
      ],
      [
        140.559998,
        "2023-01-09T12:00:00+01:00"
      ],
      [
        137.669998,
        "2023-01-09T13:00:00+01:00"
      ],
      [
        143.570007,
        "2023-01-09T14:00:00+01:00"
      ],
      [
        151.020004,
        "2023-01-09T15:00:00+01:00"
      ],
      [
        161.960007,
        "2023-01-09T16:00:00+01:00"
      ],
      [
        174.339996,
        "2023-01-09T17:00:00+01:00"
      ],
      [
        182.179993,
        "2023-01-09T18:00:00+01:00"
      ],
      [
        157.699997,
        "2023-01-09T19:00:00+01:00"
      ],
      [
        145.070007,
        "2023-01-09T20:00:00+01:00"
      ],
      [
        134.619995,
        "2023-01-09T21:00:00+01:00"
      ],
      [
        83.839996,
        "2023-01-09T22:00:00+01:00"
      ],
      [
        80.589996,
        "2023-01-09T23:00:00+01:00"
      ]
    ],
    "predictions": null,
    "api_predictions": null,
    "tariff_data": {
      "additional_tariffs": {
        "transmissions_net_tarif": 0.058,
        "system_tarif": 0.054,
        "el_afgift": 0.008
      },
      "tariffs": {}
    },
    "next_update": "13:07:22",
    "data_source": "Energi Data Service",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}

```

**Comment by MTrab** [comment] 2023-01-08 13:15
Duplicate of #175

**Closed by MTrab** 2023-01-08 13:15 UTC
