### ISSUE TITLE
elafgift value not updated ?

### ISSUE THREAD

**Issue by ujhede** [MTrab/energidataservice#321] opened 2023-07-01 06:15 UTC
### Describe the issue

It looks like the el_afgift attribute did not update to reflect the increase in the tax per midnight today.

I have tried reloading the integration, restartting HA and reconfiguring (with same settings) so I guess it has not been updated from the data source? 

### What version of Home Assistant Core has the issue?

2023.6.3

### What was the last working version of Home Assistant Core?

2023.6.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-energidataservice-9d1b7a08a3c437736fde7159c5d87d1b.json.txt](https://github.com/MTrab/energidataservice/files/11924787/config_entry-energidataservice-9d1b7a08a3c437736fde7159c5d87d1b.json.txt)

**Comment by cnrd** [comment] 2023-07-01 07:52
Looks like the issue is here: https://github.com/MTrab/energidataservice/blob/471a6bb48bbb950b711e2fdb3a8774344ed2aadc/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L186

Should be `>` and not `>=`

The validTo dates seems to be not inclusive [validFrom - validTo[, as the vaildTo of the previous value is 2023-07-01 and the vaildFrom of the new value is 2023-07-01

**Comment by MTrab** [comment] 2023-07-01 08:03
As it is now it is including the start/end date - your suggestion would not include these dates.
So it is correct as it is.

But as far as I see it, the values are not updated in the API yet.
Could be wrong, but I'm on vacation and only on the mobile, so I can't actually confirm it

**Comment by cnrd** [comment] 2023-07-01 08:21
<img width="1438" alt="Screenshot 2023-07-01 at 10 10 27" src="https://github.com/MTrab/energidataservice/assets/5996053/a282742d-d657-4707-91c3-62fb2a506962">

The value is already present.

With the current code it will overwrite the value.

The issue is in the following code block:
https://github.com/MTrab/energidataservice/blob/471a6bb48bbb950b711e2fdb3a8774344ed2aadc/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L181-L193

It should be:
```python
 check_date = (datetime.utcnow()).strftime("%Y-%m-%d") 
 tariff_data = {} 
 for entry in self._all_additional_tariffs: 
     if (entry["ValidFrom"].split("T"))[0] <= check_date and ( 
         entry["ValidTo"] is None 
         or (entry["ValidTo"].split("T"))[0] > check_date 
     ): 
         if not entry["Note"] in tariff_data: 
             tariff_data.update( 
                 {util_slugify(entry["Note"]): float(entry["Price1"])} 
             ) 
  
 self._additional_tariff = tariff_data 
```

i.e. the validTo should be sharply larger than the current date for the value to be considered. The valueFrom is correct, as that is including.

The issue will fix itself tomorrow as then the old value will have a validTo which is smaller than the current date, but I guess it would still be nice to fix the issue :-)

**Comment by ujhede** [comment] 2023-07-01 08:42
Just out of curiosity, is this update triggered at the normal data update time ?  (1pm'ish) 

To get correct tarifs they should update at midnight.

**Comment by MTrab** [comment] 2023-07-01 09:00
Yes of course, now I get what you meant.
Yeah, that's definitely a bug.
Will be fixed as soon as I'm back home with a PC at my hands again.
Will be a week or so though

**Comment by MTrab** [comment] 2023-07-01 09:01
> Just out of curiosity, is this update triggered at the normal data update time ? (1pm'ish)
> 
> To get correct tarifs they should update at midnight.

Tariffs refresh at midnight

**Comment by mm98** [comment] 2023-07-01 09:01
> It should be:

Just a small note. There are multiple of these checks in `/tariffs/energidataservice/__init__.py`

https://github.com/MTrab/energidataservice/blob/471a6bb48bbb950b711e2fdb3a8774344ed2aadc/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L91-L93

https://github.com/MTrab/energidataservice/blob/471a6bb48bbb950b711e2fdb3a8774344ed2aadc/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L128-L130

https://github.com/MTrab/energidataservice/blob/471a6bb48bbb950b711e2fdb3a8774344ed2aadc/custom_components/energidataservice/tariffs/energidataservice/__init__.py#L184-L186

I've changed these locally from `>=` to `>` and it works. @MTrab if you want any of us to make PR, please let us know.

**Comment by cnrd** [comment] 2023-07-01 09:04
Thanks @mm98 was about to write exactly the same.

@MTrab Enjoy your vacation, and thanks for all the work you are doing on this!

**Comment by MTrab** [comment] 2023-07-01 09:05
PRs are more than welcome.
But wouldn't be merged until I'm home where I can check the code.

**Comment by mm98** [comment] 2023-07-01 09:10
> PRs are more than welcome. But wouldn't be merged until I'm home where I can check the code.

PR added 😎☀️

**Closed** 2023-07-10 14:04 UTC
Labels: bug
